[package]
name = "kitu-unity-ffi"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
kitu-core = { path = "../kitu-core" }
kitu-runtime = { path = "../kitu-runtime" }
kitu-transport = { path = "../kitu-transport" }
